settings:
  title: 'Status Page'
  url: 'https://kidwen.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-home # unique identifier
    name: kidwen.top
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://kidwen.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: next-chat
    name: nc.kidwen.top
    description: 'next chat with ai model.'
    url: 'https://nc.kidwen.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: img-share
    name: img.kidwen.top
    description: 'Share you img.'
    url: 'https://img.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: file-share
    name: file.kidwen.top
    description: 'Share you file.'
    url: 'https://file.kidwen.top/'
    method: GET
    expectStatus: 200
