settings:
  title: 'Status Page'
  url: 'https://kidwen.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-home # unique identifier
    name: kidwen.top
    description: 'My main home page.' # default=empty
    url: 'https://kidwen.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: main-blog
    name: blog.kidwen.top
    description: 'My main blog.'
    url: 'https://blog.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: notion-blog
    name: nx.kidwen.top
    description: 'My main blog.'
    url: 'https://nx.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: lobe-hub
    name: lobe.kidwen.top
    description: 'Lobe hub chat with ai model.'
    url: 'https://lobe.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: next-chat
    name: nc.kidwen.top
    description: 'Next chat with ai model.'
    url: 'https://nc.kidwen.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: chat-free
    name: chat.kidwen.top
    description: 'Chat with free model.'
    url: 'https://chat.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: pandora-chat
    name: pandora.kidwen.top
    description: 'Proxy gpt by pandora.'
    url: 'https://pandora.kidwen.top/'
    method: GET
    expectStatus: 302

  - id: img-share
    name: img.kidwen.top
    description: 'Share your img.'
    url: 'https://img.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: file-share
    name: file.kidwen.top
    description: 'Share your file.'
    url: 'https://file.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: alist
    name: alist.kidwen.top
    description: 'Save and share file.'
    url: 'https://alist.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: bookmark
    name: nav.kidwen.top
    description: 'My bookmark.'
    url: 'https://nav.kidwen.top/'
    method: GET
    expectStatus: 200

  - id: word-press
    name: kidwen.serv00.net
    description: 'A word press site.'
    url: 'https://kidwen.serv00.net/'
    method: GET
    expectStatus: 200

  - id: angular-site
    name: ng.kidwen.top
    description: 'An angular site.'
    url: 'https://ng.kidwen.top/'
    method: GET
    expectStatus: 200
